# Generated by Django 5.2.12 on 2026-04-20 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page_title",
                    models.CharField(default="We'd love to hear from you.", max_length=150),
                ),
                (
                    "intro",
                    models.TextField(
                        default="Questions about gifting, events, subscriptions, or custom boxes? Our team is here to help."
                    ),
                ),
                (
                    "inquiry_email",
                    models.EmailField(default="hello@nestandwhisk.com", max_length=254),
                ),
                ("business_hours", models.CharField(default="Mon–Sat · 9am–6pm", max_length=120)),
                ("studio_location", models.CharField(blank=True, max_length=160)),
                (
                    "contact_card_body",
                    models.TextField(
                        default="Email us and we’ll get back to you promptly with thoughtful, personal support."
                    ),
                ),
            ],
            options={
                "verbose_name": "contact settings",
                "verbose_name_plural": "contact settings",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("category", models.CharField(default="General", max_length=120)),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["sort_order", "question"],
            },
        ),
        migrations.CreateModel(
            name="HomepageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eyebrow",
                    models.CharField(default="Premium handcrafted cookies", max_length=120),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Delivered with warmth, elegance, and delight.", max_length=180
                    ),
                ),
                (
                    "hero_body",
                    models.TextField(
                        default="Thoughtfully baked in small batches, beautifully packed for gifting, and made to turn ordinary moments into something worth savoring."
                    ),
                ),
                ("primary_cta_label", models.CharField(default="Shop Now", max_length=50)),
                ("primary_cta_url", models.CharField(default="#", max_length=255)),
                ("secondary_cta_label", models.CharField(default="Build a Box", max_length=50)),
                ("secondary_cta_url", models.CharField(default="#", max_length=255)),
                ("tertiary_cta_label", models.CharField(default="Subscribe", max_length=50)),
                ("tertiary_cta_url", models.CharField(default="#", max_length=255)),
                ("feature_one_label", models.CharField(default="Bestseller", max_length=60)),
                ("feature_one_title", models.CharField(default="Sea Salt Caramel", max_length=120)),
                (
                    "feature_one_body",
                    models.TextField(
                        default="Buttery centers, caramel notes, and a delicate salt finish."
                    ),
                ),
                ("feature_two_label", models.CharField(default="Seasonal", max_length=60)),
                ("feature_two_title", models.CharField(default="Pistachio Rose", max_length=120)),
                (
                    "feature_two_body",
                    models.TextField(default="Elegant floral notes with a soft nutty crunch."),
                ),
                (
                    "feature_banner_label",
                    models.CharField(default="Curated gifting", max_length=60),
                ),
                (
                    "feature_banner_body",
                    models.TextField(
                        default="Luxury packaging, gift notes, and subscription-ready boxes designed to arrive beautifully."
                    ),
                ),
                ("quality_title", models.CharField(default="Small-batch quality", max_length=120)),
                (
                    "quality_body_left",
                    models.TextField(
                        default="Premium chocolate, cultured butter, fragrant vanilla, and thoughtful finishing touches."
                    ),
                ),
                (
                    "quality_body_right",
                    models.TextField(
                        default="Build-your-own boxes, curated subscriptions, and gifting experiences crafted to feel personal."
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage content",
                "verbose_name_plural": "homepage content",
            },
        ),
        migrations.CreateModel(
            name="NewsletterSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=80)),
                ("source", models.CharField(default="site", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "newsletter signup",
                "verbose_name_plural": "newsletter signups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                (
                    "body",
                    models.TextField(validators=[django.core.validators.MinLengthValidator(40)]),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=160)),
                ("seo_description", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "policy page",
                "verbose_name_plural": "policy pages",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_name", models.CharField(default="Nest & Whisk", max_length=120)),
                (
                    "tag_line",
                    models.CharField(
                        default="Premium handcrafted cookies delivered with warmth, elegance, and delight.",
                        max_length=255,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=160)),
                ("meta_description", models.TextField(blank=True)),
                (
                    "announcement_bar_text",
                    models.CharField(
                        default="Delhi NCR delivery only - same-day/next-day in select areas.",
                        max_length=255,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(default="hello@nestandwhisk.com", max_length=254),
                ),
                ("support_phone", models.CharField(blank=True, max_length=32)),
                ("instagram_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("pinterest_url", models.URLField(blank=True)),
                (
                    "footer_blurb",
                    models.TextField(
                        default="Nest & Whisk pairs the comfort of home baking with the elegance of handcrafted gifting—small-batch cookies, beautiful presentation, and a warm experience from first click to first bite."
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_name", models.CharField(max_length=120)),
                ("customer_title", models.CharField(blank=True, max_length=120)),
                ("quote", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("is_featured", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "customer_name"],
            },
        ),
    ]
