# Generated by Django 5.2.12 on 2026-04-20 15:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("headline", models.CharField(blank=True, max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cadence_days", models.PositiveSmallIntegerField(default=30)),
                ("shipment_offset_days", models.PositiveSmallIntegerField(default=15)),
                ("box_size", models.CharField(max_length=80)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("stripe_price_id", models.CharField(blank=True, max_length=120)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["billing_interval", "is_active"],
                        name="subscriptio_billing_fd13cb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past due"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("stripe_subscription_id", models.CharField(blank=True, max_length=120)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=120)),
                ("flavor_preferences", models.JSONField(blank=True, default=list)),
                ("renewal_day", models.PositiveSmallIntegerField(default=1)),
                ("next_renewal_date", models.DateField(blank=True, null=True)),
                ("next_shipment_date", models.DateField(blank=True, null=True)),
                ("paused_from", models.DateField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "latest_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_records",
                        to="orders.order",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_for", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("skipped", "Skipped"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("tracking_reference", models.CharField(blank=True, max_length=120)),
                ("shipment_notes", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_shipments",
                        to="orders.order",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="subscriptions.usersubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["status", "next_renewal_date"], name="subscriptio_status_639db6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["status", "next_shipment_date"], name="subscriptio_status_ac97f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionshipment",
            index=models.Index(
                fields=["status", "scheduled_for"], name="subscriptio_status_afe45b_idx"
            ),
        ),
    ]
