# Generated by Django 5.2.12 on 2026-04-20 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporatePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eyebrow", models.CharField(default="Corporate gifting", max_length=120)),
                (
                    "title",
                    models.CharField(
                        default="Premium cookie gifting for clients, teams, and memorable moments.",
                        max_length=180,
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        default="From elevated client gifts to polished team celebrations, Nest & Whisk creates artisan cookie experiences that feel thoughtful, giftable, and unmistakably premium."
                    ),
                ),
                (
                    "capability_title",
                    models.CharField(default="What we can tailor", max_length=120),
                ),
                (
                    "capability_body",
                    models.TextField(
                        default="Curated assortments, seasonal gifting, branded notes, premium packaging, and delivery timing planned around launches, campaigns, and events."
                    ),
                ),
                ("lead_time_title", models.CharField(default="Typical lead time", max_length=120)),
                (
                    "lead_time_body",
                    models.TextField(
                        default="Most gifting briefs can be reviewed within one to two business days, with custom event timelines and higher-volume requests handled case by case."
                    ),
                ),
                (
                    "consultation_title",
                    models.CharField(default="Why brands choose us", max_length=120),
                ),
                (
                    "consultation_body",
                    models.TextField(
                        default="Our team blends hospitality-minded service with boutique presentation, so every gifting touchpoint feels polished from the first inquiry to final delivery."
                    ),
                ),
            ],
            options={
                "verbose_name": "corporate page content",
                "verbose_name_plural": "corporate page content",
            },
        ),
        migrations.CreateModel(
            name="CorporateInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=180)),
                ("contact_name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("occasion", models.CharField(blank=True, max_length=120)),
                ("quantity_estimate", models.PositiveIntegerField(default=1)),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_250", "Under ₹20,000"),
                            ("250_500", "₹20,000 - ₹40,000"),
                            ("500_1000", "₹40,000 - ₹80,000"),
                            ("over_1000", "Over ₹80,000"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("gifting_goal", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_review", "In review"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corporate_inquiries",
                        to="marketing.campaignattribution",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corporate_inquiries",
                        to="marketing.marketingsource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corporate_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "delivery_date"], name="corporate_c_status_dbc763_idx"
                    )
                ],
            },
        ),
    ]
