# Generated by Django 5.2.12 on 2026-04-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_ingredient_highlights_product_pairing_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="allows_build_a_box",
        ),
    ]
