# Generated by Django 5.2.12 on 2026-04-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_allows_build_a_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_file",
            field=models.FileField(blank=True, upload_to="catalog/videos/"),
        ),
    ]
