# Generated by Django 5.2.12 on 2026-04-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="video_file",
            field=models.FileField(blank=True, upload_to="catalog/products/videos/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="catalog/products/"),
        ),
    ]
